package com.failforward.backend.common.api;

public enum ErrorCode {
    ANALYSIS_NOT_READY,
    ANALYSIS_TIMEOUT,
    ANALYSIS_FAILED,
    AI_UPSTREAM_ERROR,
    AI_PARSE_ERROR,
    REPORT_NOT_FOUND,
    EXPERIENCE_NOT_FOUND,
    AUTH_REQUIRED,
    FORBIDDEN,
    NETWORK_ERROR,
    VALIDATION_ERROR,
    RATE_LIMITED,
    INTERNAL_SERVER_ERROR,
    DB_WRITE_FAILED,
    RESOURCE_NOT_FOUND,
    METHOD_NOT_ALLOWED,
    MAIL_DELIVERY_FAILED
}
