CREATE TABLE chatbot_rate_limit_state (
    user_id BIGINT NOT NULL PRIMARY KEY,
    window_start DATETIME NOT NULL,
    request_count INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE chatbot_daily_token_usage (
    scope VARCHAR(50) NOT NULL PRIMARY KEY,
    usage_date DATE NOT NULL,
    used_tokens INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
