export const ERROR_CODES = {
  ANALYSIS_NOT_READY: 'ANALYSIS_NOT_READY',
  ANALYSIS_TIMEOUT: 'ANALYSIS_TIMEOUT',
  ANALYSIS_FAILED: 'ANALYSIS_FAILED',
  AI_UPSTREAM_ERROR: 'AI_UPSTREAM_ERROR',
  AI_PARSE_ERROR: 'AI_PARSE_ERROR',
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  EXPERIENCE_NOT_FOUND: 'EXPERIENCE_NOT_FOUND',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  FORBIDDEN: 'FORBIDDEN',
  NETWORK_ERROR: 'NETWORK_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DB_WRITE_FAILED: 'DB_WRITE_FAILED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
